CREATE DATABASE 128PROJ;
USE 128PROJ;

CREATE TABLE Users (
    username VARCHAR(50) NOT NULL PRIMARY KEY,
    password VARCHAR(50) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE BMI_Data (
    username VARCHAR(50) NOT NULL,
    height FLOAT NOT NULL,
    weight FLOAT NOT NULL,
    notes VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (username) REFERENCES Users(username)
);